name: ci
on: [push, pull_request]
jobs:
  build:
    name: lint and test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [8.x, 10.x, 12.x]
    steps:
      - uses: actions/checkout@v2
      - name: Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm install
      - run: npm run lint
      - run: npm test
        if: ${{ matrix.node-version != '12.x' }}
      - uses: paambaati/codeclimate-action@v2.5.4
        with:
          coverageCommand: npm test --coverage
        if: ${{ matrix.node-version == '12.x' }}
